
ldap3.utils.tls_backportv
CertificateError)ldap3.utils.tls_backport.CertificateError"builtins.ValueErrorj36j37j38j39j310j311j312j313u
match_hostname'ldap3.utils.tls_backport.match_hostname*
cert*
hostnamez36z37z38z39z310z311z312z313*¸
__annotations__(ldap3.utils.tls_backport.__annotations__W
builtins.dict[builtins.str,Any]
builtins.str"builtins.str
Any"builtins.dict*36*37*38*39*310*311*312*313