
pysftp.exceptionsØ
ConnectionException%pysftp.exceptions.ConnectionException"builtins.Exception*ƒ
__init__.pysftp.exceptions.ConnectionException.__init__"
None*X
selfN
%pysftp.exceptions.ConnectionException"%pysftp.exceptions.ConnectionException*&
host
builtins.str"builtins.str*&
port
builtins.int"builtins.intz36z37z38z39z310j36j37j38j39j310rk
message-pysftp.exceptions.ConnectionException.message
builtins.str"builtins.str*36*37*38*39*310³
CredentialException%pysftp.exceptions.CredentialException"builtins.Exception*Þ
__init__.pysftp.exceptions.CredentialException.__init__"
None*X
selfN
%pysftp.exceptions.CredentialException"%pysftp.exceptions.CredentialException*)
message
builtins.str"builtins.strz36z37z38z39z310j36j37j38j39j310rk
message-pysftp.exceptions.CredentialException.message
builtins.str"builtins.str*36*37*38*39*310a
HostKeysException#pysftp.exceptions.HostKeysException"builtins.Exceptionj36j37j38j39j310*¢
__annotations__!pysftp.exceptions.__annotations__W
builtins.dict[builtins.str,Any]
builtins.str"builtins.str
Any"builtins.dict*36*37*38*39*310