
_pytest.config.exceptionsH

UsageError$_pytest.config.exceptions.UsageError"builtins.Exception8D
	PrintHelp#_pytest.config.exceptions.PrintHelp"builtins.Exception*•
__annotations__)_pytest.config.exceptions.__annotations__W
builtins.dict[builtins.str,Any]
builtins.str"builtins.str
Any"builtins.dict