
pysftp.exceptionsä
ConnectionException%pysftp.exceptions.ConnectionException"builtins.Exception*‡
__init__.pysftp.exceptions.ConnectionException.__init__"
None*X
selfN
%pysftp.exceptions.ConnectionException"%pysftp.exceptions.ConnectionException*&
host
builtins.str"builtins.str*&
port
builtins.int"builtins.intz35z36z37z38z39z310j35j36j37j38j39j310ro
message-pysftp.exceptions.ConnectionException.message
builtins.str"builtins.str*35*36*37*38*39*310¿
CredentialException%pysftp.exceptions.CredentialException"builtins.Exception*â
__init__.pysftp.exceptions.CredentialException.__init__"
None*X
selfN
%pysftp.exceptions.CredentialException"%pysftp.exceptions.CredentialException*)
message
builtins.str"builtins.strz35z36z37z38z39z310j35j36j37j38j39j310ro
message-pysftp.exceptions.CredentialException.message
builtins.str"builtins.str*35*36*37*38*39*310e
HostKeysException#pysftp.exceptions.HostKeysException"builtins.Exceptionj35j36j37j38j39j310